### ISSUE TITLE
[React] add component page with react-router

### ISSUE THREAD

**Issue by bluetch** [bluetch/react_website#22]
I would like to add new two pages like "product" and "branding" in navBar.js, 

but it already hot code in guideline.js, could anyone help me to solve this page? 

I already stuck in this problem for many days...dangerouslySetInnerHTML, props.params.gdlName...don't understand

**Comment by EstebanBorai** [comment]
Hey! Have you received any PullRequests already? Maybe I can help!

**Comment by bluetch** [comment]
Hi @EstebanBorai ,
I really need your help, please. The code structure is hard to maintain in guideline.js, wish could help me make it better
